[package]
name = "forest_db"
description = "Database types used in Forest"
version = "0.2.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
rocksdb = { version = "0.15.0", optional = true }
sled = { version = "0.34", optional = true }
parking_lot = "0.11"
encoding = { package = "forest_encoding", version = "0.2.1" }
thiserror = "1.0"
crossbeam = { version = "0.8.1", optional = true } # TODO: Replace after we get Prometheus metrics

[features]
default = ["lumberjackdb"]
lumberjackdb = ["sled", "crossbeam"]
sleddb = ["sled"]
